[Feat] 단어장 뷰 완벽 구현 (엄근진)
Team-EverFlow/Koreasy pull request #11
Opened 2023-08-05 15:17 UTC by SeoSangtae001027

## 관련 이슈
- closes #4 

## 구현/변경 사항
- 디자인 구현 완료
- 뷰포트 밑 미디어쿼리 적용 완료
- jsdoc 타입힌트 달아 놓기

## 추가 공유 사항
- 없어용

## 스크린샷
|단어장(아이폰14pro)|단어장(아이폰se)|
|:---:|:---:|
|![image](https://github.com/Team-EverFlow/Koreasy/assets/126737931/d03e268b-cc77-4bf5-b404-7da1f4cc7255)|![image](https://github.com/Team-EverFlow/Koreasy/assets/126737931/96e67295-deb5-4a01-8997-3da22e2ffa44)|

2023-08-05 15:27 UTC, SeoSangtae001027 commented
src => components => Wordbook jsx 와 scss 만 봐주세요,,,

2023-08-05 15:31 UTC, mouiye reviewed
수고하셨습니다! bb

2023-08-05 15:39 UTC, Mule129 requested changes
styles 폴더 내에 정의된 scss 코드 임포트해서 사용하고, 미디어쿼리+px or 뷰포트 사용 정해지는대로 변경하시면 될 것 같습니다!
추가적으로 현재 components에 작성된 파일들 pages 폴더 내에 bookmark 폴더 만들어서 내부에다 넣어주시면 좋을 것 같습니다!
수고하셨어요 :D

2023-08-05 15:39 UTC, Mule129 commented on src/components/Aug4thWeek.scss
```scss
// .scss 파일
@import '../styles/colors.scss';
@import '../styles/textStyles.scss';

.ClassName {
   background-color: $default-color-system-gray-06;  // 전역 색상 변수 사용
   @include title01-heavy;  // mixin 사용된 변수 사용
}
```
이와 같이 styles/colors.scss, styles/textStyles.scss 파일을 불러와서 내부 변수 사용해주세요!

2023-08-06 09:27 UTC, gunyu1019 commented
이 브랜치에는 제가 작업한 `textSyles.scss`와 `colors.scss`가 누락되어 있습니다. 먼저 develop 브랜치와 merge 작업을 해준 다음에 해주시면 감사하겠습니다 :)

2023-08-06 09:49 UTC, gunyu1019 commented on src/components/Wordbook.scss
> +    left: 0%;
Unit of measure '%' is redundant.
보통 값이 0이라면 단위는 생략합니다.

2023-08-06 09:49 UTC, gunyu1019 commented on src/components/Wordbook.scss
> +    top: 0%;
Unit of measure '%' is redundant.
보통 값이 0이라면 단위는 생략합니다.

```css
left: 0;
```

2023-08-06 09:50 UTC, gunyu1019 commented on src/components/Wordbook.scss
> +            left: 0px;
Unit of measure 'px' is redundant.
보통 값이 0이라면 단위는 생략합니다.

```css
left: 0;
```

2023-08-06 09:50 UTC, gunyu1019 commented on src/components/Wordbook.scss
> +            right: 0px;
Unit of measure 'px' is redundant.
보통 값이 0이라면 단위는 생략합니다.

```css
right: 0;
```

2023-08-06 09:50 UTC, gunyu1019 commented on src/components/Wordbook.scss
> +        padding: 0px 20px;
Unit of measure 'px' is redundant.
보통 값이 0이라면 단위는 생략합니다.

```css
padding: 0 20px;
```

2023-08-06 09:59 UTC, gunyu1019 commented on src/components/Wordbook.scss
> +        font-family: Pretendard;
font-family, font-size, font-style, font-weight, line-height 를 직접 지정하시는 것보다 TextStyle에 있는 title01-heavy를 불러오는 것을 권장드립니다.
```suggestion
        @include title01-heavy;
```

2023-08-06 10:01 UTC, gunyu1019 commented on src/components/Wordbook.scss
> +                        font-family: Pretendard;
font-family, font-size, font-style, font-weight, line-height 를 직접 지정하시는 것보다 TextStyle에 있는 title02-bold를 불러오는 것을 권장드립니다.
```suggestion
        @include title02-heavy;
```

2023-08-06 10:01 UTC, gunyu1019 commented on src/components/Wordbook.scss
> +                        font-family: Pretendard;
font-family, font-size, font-style, font-weight, line-height 를 직접 지정하시는 것보다 TextStyle에 있는 body01-regular를 불러오는 것을 권장드립니다.
```suggestion
        @include body01-regular;
```

2023-08-06 10:04 UTC, gunyu1019 commented on src/components/Aug4thWeek.scss
> +          font-family: Pretendard;
font-family, font-size, font-style, font-weight, line-height 를 직접 지정하시는 것보다 TextStyle에 있는 title02-bold를 불러오는 것을 권장드립니다.
```suggestion
          @include title02-bold;
```

2023-08-06 10:04 UTC, gunyu1019 commented on src/components/Aug4thWeek.scss
> +          font-family: Pretendard;
font-family, font-size, font-style, font-weight, line-height 를 직접 지정하시는 것보다 TextStyle에 있는 body01-medium를 불러오는 것을 권장드립니다.
```suggestion
          @include body01-medium;
```

2023-08-06 10:05 UTC, gunyu1019 commented on src/components/Aug4thWeek.scss
> +          font-family: Pretendard;
font-family, font-size, font-style, font-weight, line-height 를 직접 지정하시는 것보다 TextStyle에 있는 body01-medium를 불러오는 것을 권장드립니다.
```suggestion
          @include body01-medium;
```

2023-08-06 10:05 UTC, gunyu1019 commented on src/components/Aug4thWeek.scss
> +          font-family: Pretendard;
font-family, font-size, font-style, font-weight, line-height 를 직접 지정하시는 것보다 TextStyle에 있는 body01-medium를 불러오는 것을 권장드립니다.
```suggestion
          @include body01-medium;
```

2023-08-06 10:07 UTC, gunyu1019 commented on src/components/Aug4thWeek.scss
> +      font-family: Pretendard;
font-family, font-size, font-style, font-weight, line-height 를 직접 지정하시는 것보다 TextStyle에 있는 title01-heavy를 불러오는 것을 권장드립니다.
```suggestion
          @include title01-heavy;
```

2023-08-06 10:16 UTC, gunyu1019 requested changes
위 사항을 변경해주시면 반영해주시면 좋겠습니다.

2023-08-06 10:16 UTC, gunyu1019 commented on src/components/Aug4thWeek.jsx
> +                <div className="company-name">
해당 부분 소스코드가 아래(`src/components/Wordbook.jsx`)의 48번째 줄과 중복됩니다. 이 부분은 다른 디자인 요소와도 중복되는 것으로 확인되어 컴포넌트로 분리했으면 좋겠습니다. 
```jsx
            <div className="header">
                <div className="ServiceName">
                    Koreasy
                    <img
                        src={ProfileIcon}
                        alt="Profile"
                        className="ProfileIcon"
                    />
                </div>
            </div>
            <div className="Space" />
```

2023-08-13 04:52 UTC, Mule129 approved these changes
수고하셨습니다! 아래 코멘트 참고하시면 좋을 것 같습니다!

2023-08-13 04:52 UTC, Mule129 commented on src/pages/wordbookPage/WordBook.jsx
> +                            <img className="line-word" src={Line} alt="Line" />
component 폴더 내에 Divider.jsx 컴포넌트가 존재합니다! 
```suggestion
                            <Divier />
```
```jsx
import '../../components/Divider';
```
임포트해서 사용해주시면 될 것 같습니다

2023-08-13 04:52 UTC, Mule129 commented on src/pages/wordweekPage/WordWeek0.jsx
> +                                </div>
```suggestion
                                <button className="example">
                                    <div
                                        className="item-example"
                                        onClick={() =>
                                            handleExampleToggle(content.wordId)
                                        }
                                    >
                                        {isVisible(content.wordId)
                                            ? 'Hide'
                                            : 'About Word'}
                                    </div>
                                </button>
```
버튼은 div 태그 대신 button 태그를 사용하는게 적절한 것 같습니다!

2023-08-13 04:52 UTC, Mule129 commented on src/pages/wordweekPage/WordWeek0.jsx
> +                        <img className="line-week" src={Line} alt="Line" />
component 폴더 내에 Divider.jsx 컴포넌트가 존재합니다! 
```suggestion
                        <Divier />
```
```jsx
import '../../components/Divider';
```
임포트해서 사용해주시면 될 것 같습니다

2023-08-13 04:52 UTC, Mule129 commented on src/styles/wordbookStyles/WordBook.scss
> +    height: 844px;
```suggestion

```
백그라운드 높이를 지정하진 않아도 될 것 같습니다!

2023-08-13 04:52 UTC, Mule129 commented on src/styles/wordweekStyles/WordWeek0.scss
> +    height: 844px;
```suggestion

```
백그라운드 높이를 지정하지 않아도 될 것 같습니다! 또는 
```jsx
height: 100vh;
```
이와같이 사용하시는게 좋을 것 같습니다

2023-08-13 06:02 UTC, gunyu1019 approved these changes
수고하셨습니다!!

2023-08-13 06:04 UTC, HanGyeongjun approved these changes
코드 수정 제안사항 반영된 것 확인했습니다!
수고하셨습니다!

2023-08-13 06:21 UTC, merged