[Feat] Profile View
Team-EverFlow/Koreasy pull request #37
Opened 2023-08-08 11:03 UTC by gunyu1019

## 관련 이슈
- closes #14 

## 구현/변경 사항
- 프로필 뷰 작업
- PageTitle 비활성화 안되는 버그

## 추가 공유 사항
- #36 Pull Request를 Merge하고 해당 작업을 브랜치를 Merge해야합니다.

## 스크린샷
|Galaxy S8+|iPhone 12 Pro|
|:---:|:---:|
|![localhost_3000_(Samsung Galaxy S8+) (1)](https://github.com/Team-EverFlow/Koreasy/assets/16767890/3c5bc0c8-87e0-43b2-b805-c6afc7a03bae)|![localhost_3000_(iPhone 12 Pro) (3)](https://github.com/Team-EverFlow/Koreasy/assets/16767890/2c5589b6-6fdd-4b47-87ae-c5a1afcb57d7)|

2023-08-08 11:07 UTC, gunyu1019 commented
아 잠만. 잘못이해했다 ㅋㅋ. 체크바 없앨께요 ~

2023-08-08 11:09 UTC, gunyu1019 commented
#36 Pull Requests에서만 응답형 뱃지가 적용된 상태입니다. 해당 브랜치에서는 작동하지 않습니다 :(

2023-08-08 11:57 UTC, Mule129 requested changes
수고하셨습니다! right_arrow만 Chevrion 컴포넌트 사용으로 수정 부탁드립니다 :D

2023-08-08 11:57 UTC, Mule129 commented on src/pages/Profile.jsx
> +
```suggestion
import Chevrion from '../components/Chevrion';

```
Chevrion component import

2023-08-08 11:57 UTC, Mule129 commented on src/pages/Profile.jsx
> +                        <div className={'my-badge-right-arrow-icon'} />
```suggestion
                        <div className={'my-badge-right-arrow-icon'}>
                            <Chevrion direction='Right' color='MainColor' />
                        </div>
```

2023-08-08 11:57 UTC, Mule129 commented on src/styles/Profile.scss
> +    }
```suggestion
        div.my-badge-right-arrow-icon {
            width: 24px;
            height: 32px;
            flex-shrink: 0;
        }
    }
```

div class edit(Chevrion box)

2023-08-08 12:47 UTC, HanGyeongjun commented on src/assets/images/right_arrow.svg
굿굿 👍🏻

2023-08-08 12:51 UTC, mouiye approved these changes
수고하셨습니다 bb

2023-08-09 08:08 UTC, Mule129 approved these changes
수고하셨습니다 :D

2023-08-09 08:11 UTC, merged