[Fix] #40 - Fixed className duplication
Team-EverFlow/Koreasy pull request #41
Opened 2023-08-08 13:53 UTC by Mule129

## 관련 이슈
- closes #40

## 구현/변경 사항
- className 중복 문제 해결

## 스크린샷
|MainView|
|:---:|
|![image](https://github.com/Team-EverFlow/Koreasy/assets/51021398/629f1bcd-7e6a-472d-a725-ea0ae4e88870)|

2023-08-08 16:16 UTC, gunyu1019 requested changes
위 한 가지만 수정해주시면 좋을 것 같습니다. 열심히 하셨군요. 수고하셨습니다.

2023-08-08 16:16 UTC, gunyu1019 commented on src/styles/LearnTodayWord.scss
>      padding: 80px 0px;
```suggestion
   padding: 80px 0;
```

Unit of measure 'px' is redundant.
보통 값이 0이라면 단위는 생략합니다.

2023-08-09 14:15 UTC, HanGyeongjun approved these changes
기존 문제 잘 해결헤 주셨네요. 이름도 좀 더 명확해져서 읽기 수월해졌습니다. 수고하셨습니다! 👍🏻

2023-08-10 17:50 UTC, gunyu1019 approved these changes
열심하셨군요. 수고하셨습니다 :)

2023-08-10 17:59 UTC, merged