WordTestList View 구현
Team-EverFlow/Koreasy pull request #43
Opened 2023-08-09 15:39 UTC by mouiye

## 관련 이슈
- closes #3 

## 구현/변경 사항
- WordTest 선택 하는 View 구현
- Go to Test 버튼 구현
- Learn words 버튼 구현
- WordTest 제목 + 날짜 더미데이터로 구현 

## 추가 공유 사항
- 버튼 클릭시 다른 페이지로 이동되는 기능은 추후 이슈에서 구현 예정

## 스크린샷
|iphone12pro|iphoneSE|
|:---:|:---:| 
|![image](https://github.com/Team-EverFlow/Koreasy/assets/126856188/0e20dbdc-e0be-4cd0-8707-c718c9b017cb)|![image](https://github.com/Team-EverFlow/Koreasy/assets/126856188/3c3f47b7-5716-4e42-befe-a757f7de7116)|

2023-08-09 15:51 UTC, HanGyeongjun approved these changes
소소한 변경사항들만 고쳐 주시면 좋을 것 같아요! LGTM

2023-08-09 15:51 UTC, HanGyeongjun commented on src/styles/WordTestList.scss
> +    // margin-bottom: 12px;
필요 없는 주석은 지워주세요!
```suggestion
```

2023-08-09 15:51 UTC, HanGyeongjun commented on src/styles/WordTestList.scss
> +    // margin-top: 12px;
too
```suggestion
```

2023-08-09 15:51 UTC, HanGyeongjun commented on src/Router.js
> +// import Takeatest from './pages/Wordtest/Takeatest';
지워주세용
```suggestion
```

2023-08-09 15:51 UTC, HanGyeongjun commented on src/styles/WordTestList.scss
> +.babo {
클래스명 기능에 맞게 나눠주세요!

2023-08-09 15:56 UTC, SeoSangtae001027 approved these changes
고생했어요!!!

2023-08-09 15:56 UTC, SeoSangtae001027 commented on src/styles/WordTestList.scss
> +    padding-bottom: 0px;
padding-bottom: 0; 으로 바꾸면 좋을 거 같아!

2023-08-09 15:58 UTC, SeoSangtae001027 reviewed
고생했어!!!

2023-08-09 15:58 UTC, SeoSangtae001027 commented on src/styles/WordTestList.scss
> +    font-size: medium;
@include body01-bold;가 있어서 font-size 지워도 될 거 같아!

2023-08-09 15:58 UTC, SeoSangtae001027 commented on src/styles/WordTestList.scss
> +    font-size: medium;
@include body01-bold;가 있어서 font-size 지워도 될 거 같아!

2023-08-09 16:00 UTC, mouiye commented
![image](https://github.com/Team-EverFlow/Koreasy/assets/126856188/904242fd-e7c6-415a-9926-5a15efbc7373)

마진 문제 있던 부분 p 태그에서 div 태그로 변경하여 Scss 수정하였습니다.
디자인 완료 되었습니다 !

2023-08-09 16:05 UTC, Mule129 requested changes
수고하셨습니다 :D
아래 수정사항들만 참고하여 수정해주세요!

2023-08-09 16:05 UTC, Mule129 commented on src/styles/WordTestList.scss
scss 파일 내용을 각 컴포넌트별로 구분해 따로 작성해주세요.
WordTestList.jsx 와 WordTestList.scss
LearnWord.jsx 와 LearnWord.scss
WordTestTitle.jsx 와 WordTestTitle.scss
위 파일 세개로 나눠주세요.

2023-08-09 16:05 UTC, Mule129 commented on src/styles/WordTestList.scss
> +}
```scss
<div className="test-button">
    <div className="learn-button />
</div>
```
위와 같이 태그 내에 태그가 있는 구조의 경우, 클래스 계층적으로 작성해주세요.
```suggestion
.test-button {
    @include body01-bold;
    background-color: $koreasy-color-primary;
    color: $koreasy-color-white;
    border: none;
    margin-right: 12px;
    margin-left: 20px;
    width: calc((100vw - 52px) / 2);
    height: 40px;
    border-radius: 12px;
    font-size: medium;
    
            .learn-button {
            @include body01-bold;
            border: none;
            background-color: $koreasy-color-gray-06;
            color: $koreasy-color-primary;
            width: calc((100vw - 52px) / 2);
            margin-right: 20px;
            height: 40px;
            border-radius: 12px;
            font-size: medium;
        }
}
```

2023-08-09 16:05 UTC, Mule129 commented on src/pages/Wordtest/Learnwords.jsx
파일명을 LearnWords.jsx 와 같이 카멜케이스로 작성해주세요

2023-08-09 16:05 UTC, gunyu1019 approved these changes
생각보다 빠른 성장이 보기 좋군요 :) 수고하셨습니다. 
다른 분들이 웬만한 Code-Review를 해준덕에 제가 따로 지적하거나 고쳐야할 부분은 없어보입니다.

2023-08-09 16:07 UTC, gunyu1019 commented
보통 대부분 `const`랑 `function` 중 하나를 통일하여 작성하시는데, `const`와 `function`을 혼용하셔서 작성하셨네요!?
혹시 그런 이유가 있을까요?

2023-08-09 16:11 UTC, gunyu1019 commented on src/Router.js
> +// import Takeatest from './pages/Wordtest/Takeatest';
Router 쪽은 View 개발하는 브랜치마다 전부 다르게 작성되고 있어 Conflict가 발생하고 있습니다. 
이 부분에 대해서 논의가 필요해보입니다.

2023-08-09 16:52 UTC, gunyu1019 requested changes
전반적으로 소스코드를 잘구성하셨습니다. 
많은 소스코드를 작성해보시고 읽어보신다면, 충분히 성장할 수 있을 것이라고 생각합니다.

위 디자인적인 코멘트만 개선하시면 좋을 것 같습니다. 
다시 한 번 말씀드리지만, 진심으로 수고하셨습니다.

2023-08-09 16:52 UTC, gunyu1019 commented on src/pages/Wordtest/WordtestTitle.jsx
> +import LearnWords from './LearnWords';
```suggestion
import LearnWords from './Learnwords';
```
파일명은 `Learnwords.jsx`로 설정되어있는데, `LearnWords.jsx`를 불러오려고 하고 있습니다.
파일명을 변경하거나 위 소스코드 처럼 불러오는 `Learnwords`로 변경해야할 것 같습니다.

2023-08-09 16:52 UTC, gunyu1019 commented on src/styles/WordTestList.scss
> +    margin-left: 20px;
```suggestion
    margin-bottom: 4px;
```
`p` 태그를 사용하면 margin-bottom에 `1rem`이라는 공백이 생기게 됩니다.
이 경우를 방지하기 위해 margin 값을 초기화해주셔야합니다.
아래 리뷰에 후술하겠습니다.

2023-08-09 16:52 UTC, gunyu1019 commented on src/styles/WordTestList.scss
> +    margin-left: 20px;
```suggestion
    margin: 0;
```
이 역시 `p` 태그를 사용함으로써 아래에 `margin-bottom`에 공백이 생깁니다.

2023-08-09 16:52 UTC, gunyu1019 commented on src/styles/WordTestList.scss
> +.word-test-list-title {
```suggestion
.word-test-list-title {
    margin: 0 20px 12px 20px;
```
`big-title`에 있는 `margin-left: 20px`가 `small-title`에 있는 `margin-left: 20px`와 중복됩니다.

이럴 경우에는 중복된 소스코드를 지양하기 위해 `<div>`로 묶어준 다음에 한 번에 간격을 주는 것을 권장합니다.
`margin`을 사용할 경우 上-右-下-左 (상-우-하-좌) 순으로 간격을 주게됩니다.

이미 위쪽으로는 `babo`라는 클래스를 통해 12px를 주었으므로 0으로 두어야 합니다.
다만, 좌측-우측에는 20px를 줘야하므로 우와 좌 값으로 20px를 설정해주었습니다.
하단에는 12px 공백을 줘야하므로 하 값으로도 12px를 주었습니다.

2023-08-09 16:52 UTC, gunyu1019 commented on src/styles/WordTestList.scss
> +}
`word-test-list-view-name` 태그에 `margin-top: 32px`가 누락되었습니다. 지금은 PageTitle의 비활성화 버그로 인해 공백이 있는 것처럼 보이지만 실제로 develop와 Merge를 한 다음에 웹사이트를 다시보게 된다면, margin-top이 존재하지 않게 됩니다. 위 클래스에 margin-top 값을 줘야한다고 봅니다.

위에 Mule님이 길게 지적한 사항으로 인해 suggestion이 어렵습니다. 따라서 아래와 같이 클래스 부분에 덮어씌워주시면 될 것 같습니다.
```scss
    margin: 32px 20px 0 20px;
```

이 경우 상단에는 32px의 공백과 좌-우에는 20px의 공백을 주게됩니다.

2023-08-10 05:46 UTC, mouiye commented on src/styles/WordTestList.scss
> +    margin-left: 20px;
제가 확인하였을 때, big-title과 small-title에서 `p` 태그가 아닌 `div`태그를 사용한 것으로 보입니다.
혹시 제가 놓치고 있는 부분이 있을 수도 있을 것 같은데, `scss` 파일이 아닌 `jsx` 파일에서 코드 리뷰 한 번만 더 달아주실 수 있을까요?

2023-08-10 06:48 UTC, mouiye commented
변경사항 적용이 되지 않아 새로운 PR 올리겠습니다.

2023-08-10 06:53 UTC, gunyu1019 commented on src/styles/WordTestList.scss
> +    margin-left: 20px;
[#aec899... ([Style] 코드리뷰 반영)](https://github.com/Team-EverFlow/Koreasy/pull/43/commits/aec89977ac2aba29e732b4706e0d6eae15cd38b8) 커밋에서 [src/pages/Wordtest/WordtestTitle.jsx](https://github.com/Team-EverFlow/Koreasy/pull/43/commits/aec89977ac2aba29e732b4706e0d6eae15cd38b8#diff-d700b20513aea2ffd61228f096d5250476da18ee78a48717d78ef82a8dd21a79) 파일 내에 있는 9번째 줄과 10번째 줄에서 `p`태그를 사용했습니다. 지금은 big-title과 small-title을 `p` 태그가 아닌 `div` 태그로 변경된 사실을 확인하였습니다.

그러나 보통 `div` 태그는 요소를 그룹으로 묶을 때 사용합니다. 저 상황에서는 그룹으로 묶는 것이 아닌 하나의 스타일을 정의한 것이기 때문에 `span` 사용을 권장하고 싶습니다. ([관련자료](https://blog.hubspot.com/website/span-vs-div#html))

2023-08-10 07:12 UTC, gunyu1019 approved these changes
변경 사항 모두 확인하였습니다. 수고하셨습니다 :)
위 Review는 선택사항입니다. 권장사항이므로 반영하셔도 되고, 냅두셔도 기능에 지장이 없어 보입니다.

2023-08-10 07:12 UTC, gunyu1019 commented on src/pages/wordTest/WordTestTitle.jsx
> +                <div className="small-title">{date}</div>
```suggestion
                <span className="big-title">{test}</span>
                <span className="small-title">{date}</span>
```
보통 `div`는 여러 태그를 그룹으로 묶을때 사용합니다. 이런 하나의 요소에 디자인 하는 상황에서는 `span` 태그가 적절해보입니다.
* [#참고자료 1](https://www.geeksforgeeks.org/difference-between-div-and-span-tag-in-html/)
* [#참고자료 2](https://blog.hubspot.com/website/span-vs-div#html)

2023-08-10 07:14 UTC, Mule129 approved these changes
변경사항 확인 완료하였습니다 :D 수고하셨습니다!

2023-08-10 07:20 UTC, merged